[[permission]]
identifier = "allow-create-product"
description = "Allows creating a product."
commands.allow = ["pizza:create_product"]

[[permission]]
identifier = "allow-get-products"
description = "Allows retrieving products."
commands.allow = ["pizza:get_products"]

[[permission]]
identifier = "allow-update-product"
description = "Allows updating a product."
commands.allow = ["pizza:update_product"]

[[permission]]
identifier = "allow-delete-product"
description = "Allows deleting a product."
commands.allow = ["pizza:delete_product"]

[[permission]]
identifier = "allow-get-orders"
description = "Allows retrieving orders."
commands.allow = ["pizza:get_orders"]

[[permission]]
identifier = "allow-create-order"
description = "Allows creating an order."
commands.allow = ["pizza:create_order"]

[[permission]]
identifier = "allow-get-coupons"
description = "Allows retrieving coupons."
commands.allow = ["pizza:get_coupons"]

[[permission]]
identifier = "allow-create-coupon"
description = "Allows creating a coupon."
commands.allow = ["pizza:create_coupon"]

[[permission]]
identifier = "allow-print-receipt"
description = "Allows printing a receipt."
commands.allow = ["pizza:print_receipt"]
