name: Publish Tauri App
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: windows-latest  # or use matrix for multi-platform
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Install WebView2 (Windows only)
        run: |
          $path = "$env:TEMP\\Webview2Setup.exe"
          Invoke-WebRequest "https://go.microsoft.com/fwlink/?LinkId=2124703" -OutFile $path
          Start-Process $path -Args "/silent /install" -Wait
          $path = "$env:TEMP\\Webview2Setup.exe"
          Invoke-WebRequest "https://go.microsoft.com/fwlink/?LinkId=2124703" -OutFile $path
          Start-Process $path -Args "/silent /install" -Wait
      - run: npm install
      - run: npm run build
      - run: npm run tauri build -- --target x86_64-pc-windows-msvc
      - uses: softprops/action-gh-release@v1
        with:
          tag_name: release-${{ github.sha }}
          name: Windows Build ${{ github.sha }}
          files: src-tauri/target/release/bundle/msi/*.msi
